# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GCS.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_N_GCS(object):
    def setupUi(self, N_GCS):
        N_GCS.setObjectName("N_GCS")
        N_GCS.resize(1920, 1080)
        N_GCS.setFocusPolicy(QtCore.Qt.ClickFocus)
        N_GCS.setStyleSheet("background: rgb(255, 255, 255)\n"
"")
        self.centralwidget = QtWidgets.QWidget(N_GCS)
        self.centralwidget.setObjectName("centralwidget")
        self.WindowStackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.WindowStackedWidget.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.WindowStackedWidget.setObjectName("WindowStackedWidget")
        self.startPage = QtWidgets.QWidget()
        self.startPage.setObjectName("startPage")
        self.logo = QtWidgets.QWidget(self.startPage)
        self.logo.setGeometry(QtCore.QRect(840, 340, 251, 231))
        self.logo.setStyleSheet("background: url(:/logo/Nonamed-logo.png);\n"
"background-color: transparent;")
        self.logo.setObjectName("logo")
        self.logo_name = QtWidgets.QLabel(self.startPage)
        self.logo_name.setGeometry(QtCore.QRect(820, 580, 271, 111))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.logo_name.setFont(font)
        self.logo_name.setFocusPolicy(QtCore.Qt.NoFocus)
        self.logo_name.setAlignment(QtCore.Qt.AlignCenter)
        self.logo_name.setWordWrap(False)
        self.logo_name.setObjectName("logo_name")
        self.WindowStackedWidget.addWidget(self.startPage)
        self.mainPage = QtWidgets.QWidget()
        self.mainPage.setStyleSheet("")
        self.mainPage.setObjectName("mainPage")
        self.SettingStacked = QtWidgets.QStackedWidget(self.mainPage)
        self.SettingStacked.setGeometry(QtCore.QRect(30, 60, 240, 241))
        self.SettingStacked.setStyleSheet("background-color: white;")
        self.SettingStacked.setObjectName("SettingStacked")
        self.Serial = QtWidgets.QWidget()
        self.Serial.setObjectName("Serial")
        self.label = QtWidgets.QLabel(self.Serial)
        self.label.setGeometry(QtCore.QRect(10, 30, 64, 15))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_9 = QtWidgets.QLabel(self.Serial)
        self.label_9.setGeometry(QtCore.QRect(10, 60, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.Serial)
        self.label_10.setGeometry(QtCore.QRect(10, 90, 64, 15))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.Serial)
        self.label_11.setGeometry(QtCore.QRect(10, 120, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.Serial)
        self.label_12.setGeometry(QtCore.QRect(10, 150, 64, 15))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.Serial)
        self.label_13.setGeometry(QtCore.QRect(10, 180, 64, 15))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.groupBox = QtWidgets.QGroupBox(self.Serial)
        self.groupBox.setGeometry(QtCore.QRect(0, 10, 241, 191))
        self.groupBox.setStyleSheet("")
        self.groupBox.setObjectName("groupBox")
        self.PortComboBox = QtWidgets.QComboBox(self.groupBox)
        self.PortComboBox.setGeometry(QtCore.QRect(130, 10, 110, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.PortComboBox.setFont(font)
        self.PortComboBox.setObjectName("PortComboBox")
        self.BaudComboBox = QtWidgets.QComboBox(self.groupBox)
        self.BaudComboBox.setGeometry(QtCore.QRect(130, 40, 110, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.BaudComboBox.setFont(font)
        self.BaudComboBox.setObjectName("BaudComboBox")
        self.DataComboBox = QtWidgets.QComboBox(self.groupBox)
        self.DataComboBox.setGeometry(QtCore.QRect(130, 70, 110, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.DataComboBox.setFont(font)
        self.DataComboBox.setObjectName("DataComboBox")
        self.FlowComboBox = QtWidgets.QComboBox(self.groupBox)
        self.FlowComboBox.setGeometry(QtCore.QRect(130, 100, 110, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.FlowComboBox.setFont(font)
        self.FlowComboBox.setObjectName("FlowComboBox")
        self.ParityComboBox = QtWidgets.QComboBox(self.groupBox)
        self.ParityComboBox.setGeometry(QtCore.QRect(130, 130, 110, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.ParityComboBox.setFont(font)
        self.ParityComboBox.setObjectName("ParityComboBox")
        self.StopComboBox = QtWidgets.QComboBox(self.groupBox)
        self.StopComboBox.setGeometry(QtCore.QRect(130, 160, 110, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.StopComboBox.setFont(font)
        self.StopComboBox.setObjectName("StopComboBox")
        self.SerialConnectButton = QtWidgets.QPushButton(self.Serial)
        self.SerialConnectButton.setGeometry(QtCore.QRect(10, 210, 221, 28))
        self.SerialConnectButton.setStyleSheet("")
        self.SerialConnectButton.setText("")
        self.SerialConnectButton.setObjectName("SerialConnectButton")
        self.groupBox.raise_()
        self.label.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.SerialConnectButton.raise_()
        self.SettingStacked.addWidget(self.Serial)
        self.Values = QtWidgets.QWidget()
        self.Values.setObjectName("Values")
        self.AltitudeLabel = QtWidgets.QLabel(self.Values)
        self.AltitudeLabel.setGeometry(QtCore.QRect(93, 28, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(True)
        font.setWeight(75)
        self.AltitudeLabel.setFont(font)
        self.AltitudeLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.AltitudeLabel.setObjectName("AltitudeLabel")
        self.SpeedLabel = QtWidgets.QLabel(self.Values)
        self.SpeedLabel.setGeometry(QtCore.QRect(65, 100, 161, 16))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(True)
        font.setWeight(75)
        self.SpeedLabel.setFont(font)
        self.SpeedLabel.setObjectName("SpeedLabel")
        self.TimeLabel = QtWidgets.QLabel(self.Values)
        self.TimeLabel.setGeometry(QtCore.QRect(85, 165, 101, 25))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(True)
        font.setWeight(75)
        self.TimeLabel.setFont(font)
        self.TimeLabel.setObjectName("TimeLabel")
        self.Altitude_Label = QtWidgets.QLabel(self.Values)
        self.Altitude_Label.setGeometry(QtCore.QRect(120, 60, 21, 16))
        self.Altitude_Label.setObjectName("Altitude_Label")
        self.Speed_Label = QtWidgets.QLabel(self.Values)
        self.Speed_Label.setGeometry(QtCore.QRect(120, 130, 21, 16))
        self.Speed_Label.setObjectName("Speed_Label")
        self.Time_Label = QtWidgets.QLabel(self.Values)
        self.Time_Label.setGeometry(QtCore.QRect(100, 200, 61, 16))
        self.Time_Label.setObjectName("Time_Label")
        self.SettingStacked.addWidget(self.Values)
        self.Gain = QtWidgets.QWidget()
        self.Gain.setObjectName("Gain")
        self.RpyTableWidget = QtWidgets.QTableWidget(self.Gain)
        self.RpyTableWidget.setGeometry(QtCore.QRect(0, 10, 241, 231))
        self.RpyTableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.RpyTableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.RpyTableWidget.setObjectName("RpyTableWidget")
        self.RpyTableWidget.setColumnCount(3)
        self.RpyTableWidget.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.RpyTableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.RpyTableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.RpyTableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.RpyTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.RpyTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.RpyTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.RpyTableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        item.setFont(font)
        self.RpyTableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.RpyTableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.RpyTableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.RpyTableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.RpyTableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.RpyTableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.RpyTableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.RpyTableWidget.setItem(2, 2, item)
        self.SerialSendButton = QtWidgets.QPushButton(self.Gain)
        self.SerialSendButton.setGeometry(QtCore.QRect(4, 170, 231, 28))
        self.SerialSendButton.setText("")
        self.SerialSendButton.setObjectName("SerialSendButton")
        self.SerialRequestButton = QtWidgets.QPushButton(self.Gain)
        self.SerialRequestButton.setGeometry(QtCore.QRect(4, 210, 231, 28))
        self.SerialRequestButton.setText("")
        self.SerialRequestButton.setObjectName("SerialRequestButton")
        self.SettingStacked.addWidget(self.Gain)
        self.SettingComboBox = QtWidgets.QComboBox(self.mainPage)
        self.SettingComboBox.setGeometry(QtCore.QRect(30, 40, 240, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.SettingComboBox.setFont(font)
        self.SettingComboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.SettingComboBox.setStyleSheet("aligment: AlignHCenter;")
        self.SettingComboBox.setObjectName("SettingComboBox")
        self.SettingComboBox.addItem("")
        self.SettingComboBox.addItem("")
        self.SettingComboBox.addItem("")
        self.frame = QtWidgets.QFrame(self.mainPage)
        self.frame.setGeometry(QtCore.QRect(0, 20, 1941, 991))
        self.frame.setStyleSheet("background: url(:/map/map.PNG);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame.raise_()
        self.SettingStacked.raise_()
        self.SettingComboBox.raise_()
        self.WindowStackedWidget.addWidget(self.mainPage)
        N_GCS.setCentralWidget(self.centralwidget)

        self.retranslateUi(N_GCS)
        self.WindowStackedWidget.setCurrentIndex(0)
        self.SettingStacked.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(N_GCS)

    def retranslateUi(self, N_GCS):
        _translate = QtCore.QCoreApplication.translate
        N_GCS.setWindowTitle(_translate("N_GCS", "NGroundControl"))
        self.logo_name.setText(_translate("N_GCS", "N-GCS"))
        self.label.setText(_translate("N_GCS", "Port"))
        self.label_9.setText(_translate("N_GCS", "Baud Rate"))
        self.label_10.setText(_translate("N_GCS", "Data Bits"))
        self.label_11.setText(_translate("N_GCS", "Flow Control"))
        self.label_12.setText(_translate("N_GCS", "Parity"))
        self.label_13.setText(_translate("N_GCS", "Stop Bits"))
        self.groupBox.setTitle(_translate("N_GCS", " Port setup"))
        self.AltitudeLabel.setText(_translate("N_GCS", "Altitude(m)"))
        self.SpeedLabel.setText(_translate("N_GCS", "Ground Speed(m/s)"))
        self.TimeLabel.setText(_translate("N_GCS", "Flight Time"))
        self.Altitude_Label.setText(_translate("N_GCS", "0.0"))
        self.Speed_Label.setText(_translate("N_GCS", "0.0"))
        self.Time_Label.setText(_translate("N_GCS", "00:00:00"))
        item = self.RpyTableWidget.verticalHeaderItem(0)
        item.setText(_translate("N_GCS", "Roll"))
        item = self.RpyTableWidget.verticalHeaderItem(1)
        item.setText(_translate("N_GCS", "Pitch"))
        item = self.RpyTableWidget.verticalHeaderItem(2)
        item.setText(_translate("N_GCS", "Yaw"))
        item = self.RpyTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("N_GCS", "Kp"))
        item = self.RpyTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("N_GCS", "Ki"))
        item = self.RpyTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("N_GCS", "Kd"))
        __sortingEnabled = self.RpyTableWidget.isSortingEnabled()
        self.RpyTableWidget.setSortingEnabled(False)
        item = self.RpyTableWidget.item(0, 0)
        item.setText(_translate("N_GCS", "0.0"))
        item = self.RpyTableWidget.item(0, 1)
        item.setText(_translate("N_GCS", "0.0"))
        item = self.RpyTableWidget.item(0, 2)
        item.setText(_translate("N_GCS", "0.0"))
        item = self.RpyTableWidget.item(1, 0)
        item.setText(_translate("N_GCS", "0.0"))
        item = self.RpyTableWidget.item(1, 1)
        item.setText(_translate("N_GCS", "0.0"))
        item = self.RpyTableWidget.item(1, 2)
        item.setText(_translate("N_GCS", "0.0"))
        item = self.RpyTableWidget.item(2, 0)
        item.setText(_translate("N_GCS", "0.0"))
        item = self.RpyTableWidget.item(2, 1)
        item.setText(_translate("N_GCS", "0.0"))
        item = self.RpyTableWidget.item(2, 2)
        item.setText(_translate("N_GCS", "0.0"))
        self.RpyTableWidget.setSortingEnabled(__sortingEnabled)
        self.SettingComboBox.setItemText(0, _translate("N_GCS", "Serial"))
        self.SettingComboBox.setItemText(1, _translate("N_GCS", "Values"))
        self.SettingComboBox.setItemText(2, _translate("N_GCS", "Gain"))
import logo_rc
import map_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    N_GCS = QtWidgets.QMainWindow()
    ui = Ui_N_GCS()
    ui.setupUi(N_GCS)
    N_GCS.show()
    sys.exit(app.exec_())
