# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GCS.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_N_GCS(object):
    def setupUi(self, N_GCS):
        N_GCS.setObjectName("N_GCS")
        N_GCS.resize(1000, 800)
        N_GCS.setFocusPolicy(QtCore.Qt.ClickFocus)
        N_GCS.setStyleSheet("background: rgb(255, 255, 255)\n"
"")
        self.centralwidget = QtWidgets.QWidget(N_GCS)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(-10, 0, 1011, 800))
        self.stackedWidget.setObjectName("stackedWidget")
        self.startPage = QtWidgets.QWidget()
        self.startPage.setObjectName("startPage")
        self.logo = QtWidgets.QWidget(self.startPage)
        self.logo.setGeometry(QtCore.QRect(410, 200, 251, 231))
        self.logo.setStyleSheet("background: url(:/logo/Nonamed-logo.png);\n"
"background-color: transparent;")
        self.logo.setObjectName("logo")
        self.logo_name = QtWidgets.QLabel(self.startPage)
        self.logo_name.setGeometry(QtCore.QRect(390, 440, 271, 111))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.logo_name.setFont(font)
        self.logo_name.setFocusPolicy(QtCore.Qt.NoFocus)
        self.logo_name.setAlignment(QtCore.Qt.AlignCenter)
        self.logo_name.setWordWrap(False)
        self.logo_name.setObjectName("logo_name")
        self.stackedWidget.addWidget(self.startPage)
        self.mainPage = QtWidgets.QWidget()
        self.mainPage.setObjectName("mainPage")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.mainPage)
        self.stackedWidget_2.setGeometry(QtCore.QRect(30, 60, 250, 250))
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.Serial = QtWidgets.QWidget()
        self.Serial.setObjectName("Serial")
        self.label = QtWidgets.QLabel(self.Serial)
        self.label.setGeometry(QtCore.QRect(10, 30, 64, 15))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_9 = QtWidgets.QLabel(self.Serial)
        self.label_9.setGeometry(QtCore.QRect(10, 60, 64, 15))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.Serial)
        self.label_10.setGeometry(QtCore.QRect(10, 90, 64, 15))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.Serial)
        self.label_11.setGeometry(QtCore.QRect(10, 120, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.Serial)
        self.label_12.setGeometry(QtCore.QRect(10, 150, 64, 15))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.Serial)
        self.label_13.setGeometry(QtCore.QRect(10, 180, 64, 15))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.groupBox = QtWidgets.QGroupBox(self.Serial)
        self.groupBox.setGeometry(QtCore.QRect(0, 10, 241, 191))
        self.groupBox.setObjectName("groupBox")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(130, 10, 110, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_2.setGeometry(QtCore.QRect(130, 40, 110, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_3.setGeometry(QtCore.QRect(130, 70, 110, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.comboBox_3.setFont(font)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_4.setGeometry(QtCore.QRect(130, 100, 110, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.comboBox_4.setFont(font)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_5 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_5.setGeometry(QtCore.QRect(130, 130, 110, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.comboBox_5.setFont(font)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_6 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_6.setGeometry(QtCore.QRect(130, 160, 110, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.comboBox_6.setFont(font)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.pushButton = QtWidgets.QPushButton(self.Serial)
        self.pushButton.setGeometry(QtCore.QRect(70, 210, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.groupBox.raise_()
        self.label.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.pushButton.raise_()
        self.stackedWidget_2.addWidget(self.Serial)
        self.Values = QtWidgets.QWidget()
        self.Values.setObjectName("Values")
        self.label_4 = QtWidgets.QLabel(self.Values)
        self.label_4.setGeometry(QtCore.QRect(93, 28, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(self.Values)
        self.label_2.setGeometry(QtCore.QRect(65, 100, 161, 16))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.Values)
        self.label_5.setGeometry(QtCore.QRect(85, 175, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.Values)
        self.label_6.setGeometry(QtCore.QRect(120, 60, 21, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.Values)
        self.label_7.setGeometry(QtCore.QRect(120, 130, 21, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.Values)
        self.label_8.setGeometry(QtCore.QRect(100, 200, 51, 16))
        self.label_8.setObjectName("label_8")
        self.stackedWidget_2.addWidget(self.Values)
        self.Gain = QtWidgets.QWidget()
        self.Gain.setObjectName("Gain")
        self.tableWidget = QtWidgets.QTableWidget(self.Gain)
        self.tableWidget.setGeometry(QtCore.QRect(0, 30, 241, 181))
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        item.setFont(font)
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(2, 2, item)
        self.pushButton_2 = QtWidgets.QPushButton(self.Gain)
        self.pushButton_2.setGeometry(QtCore.QRect(80, 180, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.stackedWidget_2.addWidget(self.Gain)
        self.ComboBox = QtWidgets.QComboBox(self.mainPage)
        self.ComboBox.setGeometry(QtCore.QRect(30, 40, 250, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.ComboBox.setFont(font)
        self.ComboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ComboBox.setStyleSheet("aligment: AlignHCenter;")
        self.ComboBox.setObjectName("ComboBox")
        self.ComboBox.addItem("")
        self.ComboBox.addItem("")
        self.ComboBox.addItem("")
        self.stackedWidget.addWidget(self.mainPage)
        N_GCS.setCentralWidget(self.centralwidget)

        self.retranslateUi(N_GCS)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(N_GCS)

    def retranslateUi(self, N_GCS):
        _translate = QtCore.QCoreApplication.translate
        N_GCS.setWindowTitle(_translate("N_GCS", "Nonamed-GCS"))
        self.logo_name.setText(_translate("N_GCS", "N-GCS"))
        self.label.setText(_translate("N_GCS", "Port"))
        self.label_9.setText(_translate("N_GCS", "Baud Rate"))
        self.label_10.setText(_translate("N_GCS", "Data Bits"))
        self.label_11.setText(_translate("N_GCS", "Flow Control"))
        self.label_12.setText(_translate("N_GCS", "Parity"))
        self.label_13.setText(_translate("N_GCS", "Stop Bits"))
        self.groupBox.setTitle(_translate("N_GCS", "Serial port setup"))
        self.comboBox_2.setItemText(0, _translate("N_GCS", "110"))
        self.comboBox_2.setItemText(1, _translate("N_GCS", "300"))
        self.comboBox_2.setItemText(2, _translate("N_GCS", "600"))
        self.comboBox_2.setItemText(3, _translate("N_GCS", "1200"))
        self.comboBox_2.setItemText(4, _translate("N_GCS", "2400"))
        self.comboBox_2.setItemText(5, _translate("N_GCS", "4800"))
        self.comboBox_2.setItemText(6, _translate("N_GCS", "9600"))
        self.comboBox_2.setItemText(7, _translate("N_GCS", "14400"))
        self.comboBox_2.setItemText(8, _translate("N_GCS", "19200"))
        self.comboBox_2.setItemText(9, _translate("N_GCS", "34800"))
        self.comboBox_2.setItemText(10, _translate("N_GCS", "57600"))
        self.comboBox_2.setItemText(11, _translate("N_GCS", "115200"))
        self.comboBox_2.setItemText(12, _translate("N_GCS", "230400"))
        self.comboBox_2.setItemText(13, _translate("N_GCS", "460800"))
        self.comboBox_2.setItemText(14, _translate("N_GCS", "921600"))
        self.comboBox_3.setItemText(0, _translate("N_GCS", "7 bit"))
        self.comboBox_3.setItemText(1, _translate("N_GCS", "8bit"))
        self.comboBox_4.setItemText(0, _translate("N_GCS", "Xon/Xoff"))
        self.comboBox_4.setItemText(1, _translate("N_GCS", "hardware"))
        self.comboBox_4.setItemText(2, _translate("N_GCS", "none"))
        self.comboBox_5.setItemText(0, _translate("N_GCS", "none"))
        self.comboBox_5.setItemText(1, _translate("N_GCS", "odd"))
        self.comboBox_5.setItemText(2, _translate("N_GCS", "even"))
        self.comboBox_5.setItemText(3, _translate("N_GCS", "mark"))
        self.comboBox_5.setItemText(4, _translate("N_GCS", "space"))
        self.comboBox_6.setItemText(0, _translate("N_GCS", "1 bit"))
        self.comboBox_6.setItemText(1, _translate("N_GCS", "1.5 bit"))
        self.comboBox_6.setItemText(2, _translate("N_GCS", "2 bit"))
        self.pushButton.setText(_translate("N_GCS", "OK"))
        self.label_4.setText(_translate("N_GCS", "Altitude(m)"))
        self.label_2.setText(_translate("N_GCS", "Ground Speed(m/s)"))
        self.label_5.setText(_translate("N_GCS", "Flight Time"))
        self.label_6.setText(_translate("N_GCS", "0.0"))
        self.label_7.setText(_translate("N_GCS", "0.0"))
        self.label_8.setText(_translate("N_GCS", "00:00:00"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("N_GCS", "Roll"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("N_GCS", "Pitch"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("N_GCS", "Yaw"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("N_GCS", "Kp"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("N_GCS", "Ki"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("N_GCS", "Kd"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("N_GCS", "0.0"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("N_GCS", "0.0"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("N_GCS", "0.0"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("N_GCS", "0.0"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("N_GCS", "0.0"))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("N_GCS", "0.0"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("N_GCS", "0.0"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("N_GCS", "0.0"))
        item = self.tableWidget.item(2, 2)
        item.setText(_translate("N_GCS", "0.0"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton_2.setText(_translate("N_GCS", "OK"))
        self.ComboBox.setItemText(0, _translate("N_GCS", "Serial"))
        self.ComboBox.setItemText(1, _translate("N_GCS", "Values"))
        self.ComboBox.setItemText(2, _translate("N_GCS", "Gain"))
import logo_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    N_GCS = QtWidgets.QMainWindow()
    ui = Ui_N_GCS()
    ui.setupUi(N_GCS)
    N_GCS.show()
    sys.exit(app.exec_())
